### PR TITLE
Use journald (systemd) as source of logs

### PR DESCRIPTION
**Pull request by adrianlzt**
Added option `type=journald` to use journalctl as source of logs.
Each execution will only take the lines since the last execution.

Tests are missing (little experience with perl).

### CODE REVIEW

**Comment by lausser** [comment]
Can you also update plugins-scripts/Makefile.am and squash your commits?

**Comment by adrianlzt** [comment]
Do you have some instructions to "compile" the check?
I try with ```autoreconf```, ```configure``` and ```make``` but fails:
``
% LC_ALL=c make
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (c)
Making all in plugins-scripts
make[1]: Entering directory '/home/adrian/Documentos/TD-Soporte/dsn/check_logfiles/plugins-scripts'
make[1]: *** No rule to make target 'Debug/TraceMethods.pm', needed by 'check_logfiles'.  Stop.
make[1]: Leaving directory '/home/adrian/Documentos/TD-Soporte/dsn/check_logfiles/plugins-scripts'
make: *** [Makefile:349: all-recursive] Error 1
``

**Comment by adrianlzt** [comment]
Could you release a new version? Thanks

**Comment by adrianlzt** [comment]
Example of use:

```
$ ./check_logfiles.pl --type journald --logfile /dev/null --warningpattern session
OK - no errors or warnings|'default_lines'=5 'default_warnings'=0 'default_criticals'=0 'default_unknowns'=0
$ sudo id
uid=0(root) gid=0(root) grupos=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),19(log)
$ ./check_logfiles.pl --type journald --logfile /dev/null --warningpattern session
WARNING - (2 warnings in check_logfiles.protocol-2017-04-22-15-50-47) - abr 22 15:50:45 archer sudo[1209]: pam_unix(sudo:session): session closed for user root ...|'default_lines'=4 'default_warnings'=2 'default_criticals'=0 'default_unknowns'=0
```

**Comment by lausser** [comment]
3.8 is out!

**Pull request merged**
